config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "posts#index"
  resources :posts do
    resource :favorites, only: [:create, :destroy, :show]
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :comments, only: :destroy
  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :genres, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user 
  belongs_to :post, optional: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :genre 
  has_many :comments, foreign_key: "post_id", dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  with_options presence: true do
    validates :title
    validates :text
    validates :image
  end

  def self.search(search)
    if search
      Post.where('title LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  mount_uploader :image, ImageUploader
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites
  has_many :favorite_posts, through: :favorites, source: :post

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true, uniqueness: true
  with_options presence: true do
    validates :name
    validates :email
    validates :password
    validates :password_confirmation
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html { redirect_to post_path(params[:post_id])  }
      format.json
    end
    # redirect_to "/posts/#{comment.post.id}"
  end

  def edit
   
  end

  def update
    
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to "/posts/#{comment.post.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.build(post_id: params[:post_id])
    favorite.save
    
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = Favorite.find_by(post_id: params[:post_id], user_id: current_user.id)
    favorite.destroy
    
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  def show
    genre = Genre.find(params[:id]) 
    @posts = genre.posts
    @genres = Genre.all
    @name = genre.name
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.includes(:user).order("created_at DESC")
    @genres = Genre.all
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to root_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
    @genres = Genre.all
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  def search
    @posts = Post.search(params[:keyword])
    @genres = Genre.all
  end

  private
  def  post_params
    params.require(:post).permit(:title, :image, :text, :genre_id).merge(user_id: current_user.id)
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_to root_path
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to :back
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @favorite_posts = @user.favorite_posts
    
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.haml
%p.comment_edit
  = form_for ([@post, @comment]) do |f|
    = f.text_area :text, placeholder: "コメントする"
    = f.submit "SEND"

app/views/favorites/_favorite.html.haml
- if user_signed_in?
  - if post.favorited_by?(current_user)
    %p 
      %span お気に入り解除:
      = link_to "#{post.favorites.count}", "/posts/#{post.id}/favorites", method: :delete, remote: true
  - else
    %p
      %span お気に入り登録:
      = link_to "#{post.favorites.count}", "/posts/#{post.id}/favorites", method: :post, remote: true
- else
  %p
    %span お気に入り数:
    = "#{post.favorites.count}"

app/views/favorites/create.js.haml
$("#favorites_buttons_#{@post.id}").html("#{escape_javascript(render partial: 'favorites/favorite', locals: {post: @post})}");

app/views/favorites/destroy.js.haml
$("#favorites_buttons_#{@post.id}").html("#{escape_javascript(render partial: 'favorites/favorite', locals: {post: @post})}");

app/views/favorites/show.html.haml
- @favorite_posts.each do |post|
  %hr/
  %p
    %span ファボツイート内容:
    = link_to post., post_path(post.id)

app/views/genres/show.html.haml
.main
  .side_bar
    %h1.search_title 🔍投稿検索🔍
    = form_tag('/posts/search', method: :get, class: 'search_form') do
      = text_field_tag :keyword,'',class: 'search_form__tag'
      = submit_tag "検索", class: 'search_form__btn'
    .genre_show_name
      = @name
      の投稿一覧
    %p.side_bar__title ジャンル別の投稿
    .side_bar__list
      - @genres.each do |genre|
        = link_to "#{genre.name}","/genres/#{genre.id}",class: 'side_bar__list__btn'
  
  .content
    .content__text
      - @posts.each do |post|
        - if post.text.present?
          .content__box
            = image_tag post.image.url
            %p 📗記事の内容 📗
            .content__title
              = post.title
            .more_list
            = link_to '詳細', "/posts/#{post.id}", class: 'more_list__show', method: :get
            - if user_signed_in? && current_user.id == post.user_id
              = link_to '編集', "/posts/#{post.id}/edit", class: 'more_list__show',method: :get
              = link_to '削除', "/posts/#{post.id}", class: 'more_list__show', method: :delete
          = link_to "投稿者:#{post.user.name}", "/users/#{post.user.id}",class: 'name'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Babylife
    = csrf_meta_tags
    -# = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    -# = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    .header
      = link_to "Baby Life", root_path, class: 'header__title'
      - if user_signed_in?
        .header__btn
          = link_to "マイページ", "/users/#{current_user.id}",class: 'header__btn__all'
          = link_to "ログアウト", destroy_user_session_path, method: :delete,class: 'header__btn__all'
          = link_to  "投稿する", new_post_path, class: "header__btn__post",class: 'header__btn__all'
      - else
        .header__btn
          = link_to "ログイン", new_user_session_path, class: 'header__btn__all'
          = link_to "新規登録", new_user_registration_path, class: 'header__btn__all'



    = yield

app/views/posts/_form.html.haml
= form_for @post do |f|
  = f.label :title, "記事の内容",class: 'post_content__name'
  = f.text_area :title,class: 'post_content__name-form'

  = f.label :genre_id, "ジャンル選択", class: 'post_content__genre' 
  = f.select :genre_id, Genre.all.map { |genre| [genre.name, genre.id] }, class: 'post_content__genre-form'

  %p 写真選択
  = f.label :image,class: 'post_content__image' do
    = f.file_field :image, class: 'hidden'

  = f.label :text,"本文",class: 'post_content__text' 
  = f.text_area :text,class: 'post_content__text-form' 

  = f.submit "投稿する", class: 'post_content__submit'

app/views/posts/_main.html.haml
.main
  = render partial: 'side_bar'

  .content
    .content__text
      - @posts.each do |post|
        - if post.text.present?
          .content__box
            = image_tag post.image.url
            %p 記事の内容
            .content__title
              = post.title
            .more_list
            = link_to '詳細', "/posts/#{post.id}", class: 'more_list__show', method: :get
            - if user_signed_in? && current_user.id == post.user_id
              = link_to '編集', "/posts/#{post.id}/edit", class: 'more_list__show',method: :get
              = link_to '削除', "/posts/#{post.id}", class: 'more_list__show', method: :delete

            %div{id: "favorites_buttons_#{post.id}"}
              = render partial: 'favorites/favorite', locals: { post: post}

            %div{id: "relationships_buttons_#{post.user.id}"}
              = render partial: 'relationships/relationship', locals: { post: post}

            = link_to "投稿者:#{post.user.name}", "/users/#{post.user.id}",class: 'name'
           

app/views/posts/_side_bar.html.haml
.side_bar
  %h1.search_title 投稿検索
  = form_tag('/posts/search', method: :get, class: 'search_form') do
    = text_field_tag :keyword,'',class: 'search_form__tag'
    = submit_tag "検索", class: 'search_form__btn'
  %p.side_bar__title ジャンル別投稿
  .side_bar__list
    - @genres.each do |genre|
      = link_to "#{genre.name}","/genres/#{genre.id}",class: 'side_bar__list__btn'

app/views/posts/edit.html.haml
.post_new
  .post_content
    %h1.post_content__title 編集画面
    = render partial: 'form', locals: { posts: @post }

app/views/posts/index.html.haml
.wrapper
  -# = render "header"
  = render "main"

app/views/posts/new.html.haml
.post_new
  .post_content
    %h1.post_content__title 新規投稿
    = render partial: 'form', locals: { posts: @post }

app/views/posts/search.html.haml
.main
  = render partial: 'side_bar', locals: { posts: @genres }

  .content
    .content__text
      - @posts.each do |post|
        - if post.text.present?
          .content__box
            = image_tag post.image.url
            .content__title
              %p タイトル
              = post.title
            .content__text
              %p 本文
              = post.text
            %ul.more_list
            %li
              = link_to '詳細', "/posts/#{post.id}", method: :get
            - if user_signed_in? && current_user.id == post.user_id
              %li
                = link_to '編集', "/posts/#{post.id}/edit", method: :get
              %li
                = link_to '削除', "/posts/#{post.id}", method: :delete
            %span.name
            %a{:href => "/users/#{post.user.id}"}
              %span 投稿者
              = post.user.name

app/views/posts/show.html.haml
.main
  = render partial: 'side_bar'

  .content
    .content__main
      - if @post.text.present?
        .content__box
          = image_tag @post.image.url
          %p 記事の内容
          .content__title
            = @post.title
          %p 本文
          .content__text_show
            = simple_format(@post.text)

          .more_list
          - if user_signed_in? && current_user.id == @post.user_id
            = link_to '編集', "/posts/#{@post.id}/edit", class: 'more_list__show',method: :get
            = link_to '削除', "/posts/#{@post.id}", class: 'more_list__show', method: :delete

    .comment
      - if current_user
        = form_for ([@post, @comment]) do |f|
          = f.text_area :text, placeholder: "コメントする", class: "textbox"
          = f.submit "SEND", class: "comment-submit"
      - else
        %p === コメントの投稿には新規登録/ログインが必要です ===
      .comments
        %h4 ＜コメント一覧＞
        - if @comments
          - @comments.each do |comment|
            %p
              %strong
                = link_to comment.user.name, "/users/#{comment.user_id}"
                ：
                = comment.text
                -# - if user_signed_in? && current_user.id == @post.user_id
                -#   = link_to '削除', "/comments/#{comment.id}", method: :delete
              -# = link_to '編集', "/posts/#{@post.id}/comments/#{comment.id}/edit", method: :get

app/views/relationships/_relationship.html.haml
- if user_signed_in?
  - if current_user != post.user
    - if post.user.followed_by?(current_user)
      = link_to "フォロー済み", user_relationships_path(post.user.id), method: :delete
    - else
      = link_to "フォローする", user_relationships_path(post.user.id), method: :post

app/views/relationships/create.js.haml
$("#relationships_buttons_#{@post.user.id}").html("#{escape_javascript(render partial: 'relationships/relationship', locals: {post: @post})}");

app/views/relationships/destroy.js.haml
$("#relationships_buttons_#{@post.user.id}").html("#{escape_javascript(render partial: 'relationships/relationship', locals: {post: @post})}");

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/followers.html.haml
.follws_main
  .follws_main__content
    %h1.follws フォローしてくれている人一覧
    .follws_box
    - @users.each do |user|
      .follws_box__content
        %p.follws_box__content__title なまえ:
        = link_to user.name, user_path(user.id),class: 'follws_box__content__name'
     

app/views/users/follows.html.haml
.follws_main
  .follws_main__content
    %h1.follws フォローしている人一覧
    .follws_box
    - @users.each do |user|
      .follws_box__content
        %p.follws_box__content__title なまえ:
        = link_to user.name, user_path(user.id),class: 'follws_box__content__name'
      - if current_user != user
        - if user.followed_by?(current_user)
          %p= link_to "フォロー解除", user_relationships_path(user.id),class: 'follws_link', method: :delete

app/views/users/show.html.haml
.main
  .user_show_box
    .user_show_box__name
      = @user.name
      さんの投稿一覧
    - if current_page?(current_user) 
      = link_to 'ユーザー情報編集', edit_user_path(current_user),class:'user_show_box__name__edit', method: :get
    .relationship_box
      = link_to "フォロー", follows_user_path(@user.id), class: 'relationship_box__list'
      = link_to "フォロワー", followers_user_path(@user.id), class: 'relationship_box__list'
      - if current_user != @user
        - if @user.followed_by?(current_user)
          = link_to "フォロー済み", user_relationships_path(@user.id), class: 'relationship_box__list', method: :delete
        - else
          = link_to "フォローする", user_relationships_path(@user.id), class: 'relationship_box__list', method: :post
    .user_favorite
      %p.user_favorite__title お気に入りタイトル一覧
      - @favorite_posts.each do |post|
        .user_favorite__show
          = link_to "#{post.user.name}      #{post.title}", post_path(post.id),class: 'user_favorite__show__link', method: :get

    

   

  .content
    .content__text
      - @posts.each do |post|
        - if post.text.present?
          .content__box
            = image_tag post.image.url
            %p 📗記事の内容 📗
            .content__title
              = post.title
            %p 📕本文 📕
            .content__text_show
              = simple_format(post.text)
            .more_list
            = link_to '詳細', "/posts/#{post.id}", class: 'more_list__show', method: :get
            - if user_signed_in? && current_user.id == post.user_id
              = link_to '編集', "/posts/#{post.id}/edit", class: 'more_list__show',method: :get
              = link_to '削除', "/posts/#{post.id}", class: 'more_list__show', method: :delete
            